networks:
  network-vortex-front:

services:

  vortex-web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - network-vortex-front
    ports:
      - 4200:80
