name: CI

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Restore dependencies
        working-directory: VortexApi
        run: dotnet restore
      - name: Build the solution
        working-directory: VortexApi
        run: dotnet build --no-restore --configuration Release

  backend-style:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Run format
        working-directory: VortexApi
        run: dotnet format --verify-no-changes

  backend-tests:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Run tests
        working-directory: VortexApi
        run: dotnet test

  docker-config:
    runs-on: ubuntu-latest
    needs:
      - backend-build
    steps:
      - uses: actions/checkout@v4
      - name: Check docker compose config
        run: docker compose build
