name: CI

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Build Angular App
      working-directory: ./frontend
      run: npm run build

  frontend-style:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint

  frontend-tests:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run Angular Unit Tests
        working-directory: ./frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  docker-config:
    runs-on: ubuntu-latest
    needs:
      - frontend-build
    steps:
      - uses: actions/checkout@v4
      - name: Check docker compose config
        run: docker compose build
